spring:
  data:
    mongodb:
#      uri: mongodb://self-service-portal-admin:LzVMRm5wa3E3cmxyKy85b0F1ZXZ0WkRPTUxkNXZMSmw=@localhost:27017/self-service-portal
      host: localhost
      port: 27017
      database: self-service-portal
      username: self-service-portal-admin
      password: LzVMRm5wa3E3cmxyKy85b0F1ZXZ0WkRPTUxkNXZMSmw=
      repositories:
        type: reactive
